name: Auto Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Lint Code
        run: flake8 app tests

      - name: Run Tests
        run: python -m unittest discover -s tests
