name: Manual Pipeline

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  manual_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Manual Job
        run: echo "This workflow was triggered manually!" && python -m unittest discover -s tests
